open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let fill_rect =
    foreign "CGContextFillRect" (Types.CGContext.t @-> Types.CGRect.rect @->
      returning void)
end