open Ctypes

(* This Types_generated module is an instantiation of the Types
	 functor defined in the type_description.ml file. It's generated by
	 a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
	open Types
	open F

	module CGContext = struct
		include CGContext  (* from Types *)

		let fill_rect =
			foreign "CGContextFillRect" (t @-> CGRect.rect @-> returning void)

		let set_rgb_fill_color =
			foreign "CGContextSetRGBFillColor" (t @->
				double @-> double @-> double @-> double @-> returning void)
	end
end
